django_store/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

django_store/orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'
urlpatterns = [
    path('<int:pk>/', views.OrderDetailView.as_view(), name='detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.AddToCart.as_view(), name='add_to_cart'),
    path('cart/delete/<int:product_id>/', views.DeleteFromCart.as_view(), name='delete_from_cart'),
    path('create/', views.CreateOrderView.as_view(), name='create')
]

django_store/products/urls.py
from django.urls import path

from . import views


app_name = 'products'
urlpatterns = [
    path('', views.ProductListView.as_view(), name='list_all'),
    path('page-<int:page>/', views.ProductListView.as_view(), name='list_all_page'),
    path('<slug:category>/', views.ProductListView.as_view(), name='list'),
    path('<slug:category>/<int:pk>/', views.ProductDetailView.as_view(), name='detail'),
    path('<slug:category>/page-<int:page>/', views.ProductListView.as_view(), name='list_page'),
]

django_store/products/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(_('Категория'), max_length=40)
    slug = models.SlugField(_('Slug'))

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:list', kwargs={'category': self.slug})


class Brand(models.Model):
    name = models.CharField(_('Производитель'), max_length=40)

    class Meta:
        verbose_name = 'Производитель'
        verbose_name_plural = 'Производители'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(_('Название'), max_length=50)
    description = models.TextField(_('Описание'))
    category = models.ForeignKey(verbose_name=_('Категория'), to=Category, on_delete=models.PROTECT)
    brand = models.ForeignKey(verbose_name=_('Производитель'), to=Brand, on_delete=models.PROTECT)
    price = models.DecimalField(_('Цена'), max_digits=10, decimal_places=2)
    quantity = models.IntegerField(_('Количество'), default=20)
    available = models.BooleanField(_('Доступен'), default=True)
    image = models.ImageField(_('Изображение'), upload_to='products', default='default/image.png')

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:detail', kwargs={'category': self.category.slug, 'pk': self.pk})

    def decrease_quantity(self, quantity):
        self.quantity -= quantity
        if self.quantity == 0:
            self.available = False
        self.save()

django_store/products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic.base import View, TemplateResponseMixin, ContextMixin
from django.views.generic.list import MultipleObjectMixin
from django.views.generic.detail import SingleObjectMixin

from .models import Product, Category


class ProductListView(MultipleObjectMixin, TemplateResponseMixin, View):
    model = Product
    template_name = 'products/product_list.html'
    allow_empty = True
    paginate_by = 3

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        context = self.get_context_data()

        return self.render_to_response(context)

    def get_queryset(self):
        queryset = super().get_queryset()
        category_raw = self.kwargs.get('category')
        search_query = self.request.GET.get('q')
        sort = self.request.GET.get('sort')

        if search_query:
            return queryset.filter(name__icontains=search_query)

        if category_raw:
            category = get_object_or_404(Category, slug=category_raw)
            queryset = queryset.filter(category=category)

        if sort:
            if sort == 'priceup':
                queryset = queryset.order_by('price')
            if sort == 'pricedown':
                queryset = queryset.order_by('-price')
            if sort == 'nameup':
                queryset = queryset.order_by('name')
            if sort == 'namedown':
                queryset = queryset.order_by('-name')

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['categories'] = Category.objects.all()
        context['category'] = self.kwargs.get('category')

        return context

    def get_sort_base_url(self):
        category = self.kwargs.get('category')

        if category:
            return reverse('products:list', kwargs={'category': category})
        else:
            return reverse('products:list_all')

    def get_price_sort_url(self):
        BASE_URL = self.get_sort_base_url()

        mapping = {
            'priceup': BASE_URL + '?sort=pricedown',
            'pricedown': BASE_URL + '?sort=priceup',
        }

        return mapping.get(self.request.GET.get('sort'), BASE_URL + '?sort=pricedown')

    def get_name_sort_url(self):
        BASE_URL = self.get_sort_base_url()

        mapping = {
            'nameup': BASE_URL + '?sort=namedown',
            'namedown': BASE_URL + '?sort=nameup',
        }

        return mapping.get(self.request.GET.get('sort'), BASE_URL + '?sort=namedown')


class ProductDetailView(SingleObjectMixin, TemplateResponseMixin, View):
    model = Product
    template_name = 'products/product_detail.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)

        return self.render_to_response(context)

django_store/products/templates/products/product_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-5">
            <h4>Изображение</h4>
            <img src={{ object.image.url }} class="img-thumbnail" style="max-width: 300px; height: auto;">
        </div>
        <div class="col-md-7">
            <h4>Описание</h4>
            <table class="table">
                <tbody>
                <tr>
                    <td>Название</td>
                    <td>{{ object.name }}</td>
                </tr>
                <tr>
                    <td>Категория</td>
                    <td> {{ object.category }}</td>
                </tr>
                <tr>
                    <td>Производитель</td>
                    <td>{{ object.brand }}</td>
                </tr>
                <tr>
                    <td>Описание</td>
                    <td>{{ object.description }}</td>
                </tr>
                <tr>
                    <td>Цена</td>
                    <td>{{ object.price }} &#8381;</td>
                </tr>
                <tr>
                    <td>Доступен</td>
                    <td>
                        {% if object.available %}
                            Есть на складе
                        {% else %}
                            Нет на складе
                        {% endif %}
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        {% if user.is_authenticated %}
            <div class="col text-center">
                <a href="{% url 'orders:add_to_cart' product.id %}" class="btn btn-primary">Добавить в корзину</a>
            </div>
        {% endif %}
    </div>
{% endblock %}

django_store/products/templates/products/product_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load templatetags %}

{% block content %}
    <div class="row">
        <div class="col-md-3">
            <div class="list-group">
                <a href="{% url 'products:list_all' %}" class="list-group-item list-group-item-action">Все</a>
                {% for category in categories %}
                    <a href="{{ category.get_absolute_url }}" class="list-group-item list-group-item-action">{{ category }}</a>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-9">
            <div class="col border rounded">
                <span>Сортировать по: </span>
                <a href="{{ view.get_price_sort_url }}">Цене</a>
                <a href="{{ view.get_name_sort_url }}">Названию</a>
            </div>
            {% if ordered_list %}
                {% for product in ordered_list %}
                    {% if forloop.first %}
                        <div class="card-columns">
                    {% endif %}
                    <a href="{% url 'products:detail' product.category.slug product.id %}">
                        <div class="card" style="width: 18rem;">
                            <img src="{{ product.image.url }}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{ product.name }}</h5>
                                <p class="card-text">Цена: {{ product.price }} &#8381;</p>
                                {% if user.is_authenticated %}
                                    <a href="{% url 'orders:add_to_cart' product.id %}" class="btn btn-primary mt-2">Добавить в корзину</a>
                                {% endif %}
                            </div>
                        </div>
                    </a>
                    {% if forloop.counter|divisibleby:3 %}
                        </div>
                        <div class="card-columns">
                    {% endif %}
                    {% if forloop.last %}
                        </div>
                    {% endif %}
                {% endfor %}
            {% else %}
                {% for product in object_list %}
                    {% if forloop.first %}
                        <div class="card-columns">
                    {% endif %}
                    <a href="{% url 'products:detail' product.category.slug product.id %}">
                        <div class="card" style="width: 18rem;">
                            <img src="{{ product.image.url }}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{ product.name }}</h5>
                                <p class="card-text">Цена: {{ product.price }} &#8381;</p>
                                {% if user.is_authenticated %}
                                    <a href="{% url 'orders:add_to_cart' product.id %}" class="btn btn-primary mt-2">Добавить в корзину</a>
                                {% endif %}
                            </div>
                        </div>
                    </a>
                    {% if forloop.counter|divisibleby:3 %}
                        </div>
                        <div class="card-columns">
                    {% endif %}
                    {% if forloop.last %}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            {% if is_paginated %}
            <div class="col d-flex justify-content-center align-items-center">
                    {% if page_obj.has_previous %}
                        {% if category %}
                            <a href="{% url 'products:list_page' category=category page=1 %}{% query_transform %}" class="btn btn-primary">&laquo; Первая</a>
                            <a href="{% url 'products:list_page' category=category page=page_obj.previous_page_number %}{% query_transform %}" class="btn btn-primary ml-2">Предыдущая</a>
                        {% else %}
                            <a href="{% url 'products:list_all_page' page=1 %}{% query_transform %}" class="btn btn-primary">&laquo; В начало</a>
                            <a href="{% url 'products:list_all_page' page=page_obj.previous_page_number %}{% query_transform %}" class="btn btn-primary ml-2">Предыдущая</a>
                        {% endif %}
                    {% endif %}
            
                    <span class="mx-2">
                        Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                    </span>
            
                    {% if page_obj.has_next %}
                        {% if category %}
                            <a href="{% url 'products:list_page' category=category page=page_obj.next_page_number %}{% query_transform %}" class="btn btn-primary mr-2">Следующая</a>
                            <a href="{% url 'products:list_page' category=category page=page_obj.paginator.num_pages %}{% query_transform %}" class="btn btn-primary">Последняя &raquo;</a>
                        {% else %}
                            <a href="{% url 'products:list_all_page' page=page_obj.next_page_number %}{% query_transform %}" class="btn btn-primary mr-2">Следующая</a>
                            <a href="{% url 'products:list_all_page' page=page_obj.paginator.num_pages %}{% query_transform %}" class="btn btn-primary">Последняя &raquo;</a>
                        {% endif %}
                    {% else %}
                        <span></span>
                        <span></span>
                    {% endif %}
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}