django_store/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

django_store/orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'
urlpatterns = [
    path('<int:pk>/', views.OrderDetailView.as_view(), name='detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.AddToCart.as_view(), name='add_to_cart'),
    path('cart/delete/<int:product_id>/', views.DeleteFromCart.as_view(), name='delete_from_cart'),
    path('create/', views.CreateOrderView.as_view(), name='create')
]

django_store/products/urls.py
from django.urls import path

from . import views


app_name = 'products'
urlpatterns = [
    path('', views.ProductListView.as_view(), name='list_all'),
    path('page-<int:page>/', views.ProductListView.as_view(), name='list_all_page'),
    path('<slug:category>/', views.ProductListView.as_view(), name='list'),
    path('<slug:category>/<int:pk>/', views.ProductDetailView.as_view(), name='detail'),
    path('<slug:category>/page-<int:page>/', views.ProductListView.as_view(), name='list_page'),
]

django_store/profiles/urls.py
from django.urls import path
from django.conf import settings

from . import views


app_name = 'profiles'
urlpatterns = [
    path('', views.UserAccount.as_view(), name='account'),
    path('signup/', views.UserCreate.as_view(), name='signup'),
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', views.UserLogout.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
]

django_store/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://bootswatch.com/4/flatly/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/noty.css' %}">
    <title>
        {% block title %}
            Django-Store
        {% endblock %}
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
        <a class="navbar-brand" href="{% url 'products:list_all' %}">Django-Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mr-auto">
                {% comment %} <li class="active">
                    <a class="nav-link" href="#">Home</a>
                </li> {% endcomment %}
            </ul>
            <form action="{% url 'products:list_all' %}" method="GET" class="form-inline my-2 mx-2 my-lg-0">
                <input id="search" type="search" placeholder="Поиск..." aria-label="Поиск" name="q" class="form-control mr-sm-2">
                <button type="submit" class="btn btn-outline-success my-2 my-sm-0">Поиск</button>
            </form>
            <ul class="navbar-nav navbar-right">
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href='{% url "profiles:signup" %}'>Регистрация</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href='{% url "profiles:login" %}'>Вход</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'profiles:account' %}" class="nav-link">
                            Аккаунт: {{ user.email }}
                        </a>
                    </li>
                    {% if not request.session.cart %}
                        <li class="nav-item">
                            <span class="navbar-text mx-2">Ваша корзина пуста</span>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href='{% url "orders:cart" %}'>Корзина: {{ request.session.cart.values|length }}</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href='{% url "profiles:logout" %}'>Выход</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        {% block content %}
        {% endblock %}
    </main>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'js/noty.js' %}"></script>
    <script>
        {% if messages %}
            {% for message in messages %}
                new Noty({
                    theme: 'nest',
                    layout: 'topCenter',
                    type: '{{ message.tags }}',
                    text: '{{ message }}',
                    timeout: 3000,
                }).show();
            {% endfor %}
        {% endif %}
    </script>
</body>
</html>