django_store/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

django_store/orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'
urlpatterns = [
    path('<int:pk>/', views.OrderDetailView.as_view(), name='detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.AddToCart.as_view(), name='add_to_cart'),
    path('cart/delete/<int:product_id>/', views.DeleteFromCart.as_view(), name='delete_from_cart'),
    path('create/', views.CreateOrderView.as_view(), name='create')
]

django_store/orders/models.py
from django.urls import reverse
from django.db import models
from django.db.models import F, Sum, DecimalField
from django.utils.translation import ugettext_lazy as _

from profiles.models import Customer
from products.models import Product


class Order(models.Model):
    ORDER_PROCESS = 'process'
    ORDER_SHIPPED = 'shipped'
    ORDER_DELIVERED = 'delivered'

    ORDER_STATUS_CHOICES = (
        (ORDER_PROCESS, 'Обрабатывается'),
        (ORDER_SHIPPED, 'Отправлено', ),
        (ORDER_DELIVERED, 'Доставлено'),
    )

    customer = models.ForeignKey(verbose_name=_('Покупатель'), to=Customer, on_delete=models.CASCADE)
    order_status = models.CharField(_('Статус'), max_length=20, default=ORDER_PROCESS, choices=ORDER_STATUS_CHOICES)
    order_date = models.DateTimeField(_('Дата заказа'), auto_now_add=True)
    products = models.ManyToManyField(verbose_name=_('Товары'), to=Product, through='OrderList')

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('orders:detail', kwargs={"pk": self.pk})

    def get_total(self):
        return (
            self.orderlist_set
            .all()
            .aggregate(
                total=Sum(F('product__price')*(F('quantity')),
                output_field=DecimalField())
            )['total']
        )

        """
        Older variant:
            total = 0
            
            for ol in self.orderlist_set.all():
                total += ol.get_sum()
            
            return total
        
        This was replaced because database works faster than python with data (Read it from Two Scoops of Django)
        """


class OrderList(models.Model):
    order = models.ForeignKey(verbose_name=_('Заказ'), to=Order, on_delete=models.CASCADE)
    product = models.ForeignKey(verbose_name=_('Товар'), to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(_('Количество'), default=1)

    class Meta:
        verbose_name = 'Товары заказа'
        verbose_name_plural = 'Товары заказа'

django_store/orders/forms.py
# TODO: Create form for creating an order
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import OrderList, Order
from products.models import Product


class OrderListForm(forms.ModelForm):
    class Meta:
        model = OrderList
        fields = '__all__'

    def clean_quantity(self):
        product = self.cleaned_data.get('product')
        quantity = self.cleaned_data.get('quantity')

        if (product and quantity):
            if quantity > product.quantity:
                self.add_error('quantity', 'Product is out')
                raise forms.ValidationError(_('Product is out'), code="Invalid")

        return quantity

django_store/orders/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import View, TemplateResponseMixin
from django.views.generic.list import MultipleObjectMixin
from django.views.generic.detail import SingleObjectMixin
from django.db import transaction
from django.contrib import messages

from products.models import Product
from .models import Order, OrderList
from .forms import OrderListForm


class AddToCart(LoginRequiredMixin, View):
    login_url = 'profiles:login'

    def get(self, request, *args, **kwargs):
        cart = request.session.get('cart', {})
        product_id = str(self.kwargs['product_id'])
        if product_id in cart:
            cart[product_id] += 1
        else:
            cart[product_id] = 1
        request.session['cart'] = cart

        messages.success(request, 'Товар добавлен')

        return redirect(request.GET.get('from', 'products:list_all'))


class DeleteFromCart(LoginRequiredMixin, View):
    login_url = 'profiles:login'
    
    def get(self, request, *args, **kwargs):
        cart = request.session.get('cart')
        product_id = str(self.kwargs['product_id'])
        cart[product_id] -= 1
        if not cart[product_id]:
            del cart[product_id]
        request.session['cart'] = cart

        messages.success(request, 'Товар удален')

        return redirect('orders:cart')


class CartView(LoginRequiredMixin, MultipleObjectMixin, TemplateResponseMixin, View):
    model = Product
    template_name = 'orders/cart.html'
    paginate_by = 9
    allow_empty = True
    login_url = 'profiles:login'

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        context = self.get_context_data()

        return self.render_to_response(context)

    def get_queryset(self):
        queryset = super().get_queryset()

        # Get a category from a url if it passed else set the category to 't-shirt'
        category = self.kwargs.get('category', 't-shirt')

        return queryset.filter(category__slug=category)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Add the cart list with Product objects to the context
        cart_products = []
        for product_id in self.request.session['cart'].keys():
            product = self.model.objects.get(pk=product_id)
            cart_products.append((product, self.request.session['cart'][product_id]))
        
        context['cart_products'] = cart_products

        return context


class CreateOrderView(LoginRequiredMixin, View):
    login_url = 'profiles:login'
    
    @transaction.atomic
    def post(self, request, *args, **kwargs):
        # Populate the cart list with Product objects by IDs from the session
        cart_products = []
        for product_id in request.session['cart'].keys():
            product = Product.objects.get(pk=product_id)
            cart_products.append((product, request.session['cart'][product_id]))

        # Create customer's order
        order = Order.objects.create(customer=request.user.customer)

        # Populate a customer's order with Product objects from the cart list
        for product_tuple in cart_products:
            # order_list_item = OrderList(order=order, product=product_tuple[0], quantity=product_tuple[1])
            order_list_form = OrderListForm({'product': product_tuple[0].pk, 'order': order.pk, 'quantity': product_tuple[1]})
            if order_list_form.is_valid():
                order_list_form.save()
            else:
                transaction.set_rollback(True)
                messages.error(request, 'Ошибка создания заказа')
                return redirect('orders:cart')

        del request.session['cart']

        messages.success(request, 'Ваш заказ оформлен')

        return redirect('products:list_all')


class OrderDetailView(LoginRequiredMixin, SingleObjectMixin, TemplateResponseMixin, View):
    model = Order
    template_name = 'orders/order_detail.html'
    login_url = 'profiles:login'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)

        return self.render_to_response(context)

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        print(obj.customer, self.request.user.customer)
        if obj.customer != self.request.user.customer:
            raise PermissionDenied
        return obj

django_store/orders/templates/orders/cart.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col">
            <h4>Коризна</h4>
            {% if request.session.cart %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>Товар</th>
                            <th>Количество</th>
                            <th>Цена</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for product_tuple in cart_products %}
                            <tr>
                                <td><a href="{{ product_tuple.0.get_absolute_url }}">{{ product_tuple.0 }}</a></td>
                                <td>{{ product_tuple.1 }}</td>
                                <td>{{ product_tuple.0.price }}</td>
                                <td><a href="{% url 'orders:delete_from_cart' product_tuple.0.pk %}">Удалить</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>Ваша корзина пуста</p>
            {% endif %}
            <form action="{% url 'orders:create' %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="Сделать заказ" class="btn btn-primary">
            </form>
        </div>
    </div>
{% endblock %}

django_store/orders/templates/orders/order_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col">
            <h4>Заказ №{{ object.pk }}</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>Товар</th>
                        <th>Количество</th>
                        <th>Цена</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.orderlist_set.all %}
                        <tr>
                            <td><a href="{{ order_item.product.get_absolute_url }}">{{ order_item.product.name }}</a></td>
                            <td>{{ order_item.quantity }}</td>
                            <td>{{ order_item.product.price }}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td class="text-right" colspan="2">Сумма:</td>
                        <td>{{ object.get_total }}</td>
                    </tr>
                    <tr>
                        <td class="text-right" colspan="2">Статус:</td>
                        <td>{{ object.get_order_status_display }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}